"""SQLAlchemy 2.0 ORM models — an exact mirror of the Supabase ``pp`` schema
(see ``sql/0001_baseline.sql``), the shared data layer replacing the vendored ``db/``.

Conventions:
  * All tables live in the ``pp`` schema (``Base.metadata`` schema).
  * No ``naming_convention`` — PK/UNIQUE/CHECK keep Postgres' default auto-names, exactly as the
    applied DDL created them, so Alembic autogenerate sees an empty diff. Only the explicit
    ``idx_*`` indexes are named (to match the applied names).
  * ``*_utc`` columns are naive ``DateTime`` (TIMESTAMP WITHOUT TIME ZONE); the engine pins every
    session to UTC. ``*_local`` flight times are ``DateTime(timezone=True)`` (TIMESTAMPTZ).
  * Surrogate ``id`` columns use ``Identity()`` (GENERATED BY DEFAULT) so backfill can preserve ids.
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    Double,
    Identity,
    Index,
    Integer,
    MetaData,
    Numeric,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.sql import func


class Base(DeclarativeBase):
    metadata = MetaData(schema="pp")


# Reusable server-default snippets
_NOW = func.now()
_FALSE = text("false")


class RoutesQueue(Base):
    __tablename__ = "routes_queue"

    origin: Mapped[str] = mapped_column(String(3), primary_key=True)
    dest: Mapped[str] = mapped_column(String(3), primary_key=True)
    airline: Mapped[str] = mapped_column(String(10), primary_key=True, server_default=text("'alaska'"))
    priority_tier: Mapped[str] = mapped_column(String(4), nullable=False, server_default=text("'LOW'"))
    search_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    decayed_demand: Mapped[float] = mapped_column(Double, nullable=False, server_default=text("0"))
    last_search_at_utc: Mapped[datetime | None] = mapped_column(DateTime)
    change_rate: Mapped[float] = mapped_column(Double, nullable=False, server_default=text("0.5"))
    last_cheapest: Mapped[str | None] = mapped_column(String)
    interval_h: Mapped[float | None] = mapped_column(Double)
    last_scraped_at_utc: Mapped[datetime | None] = mapped_column(DateTime)
    next_scrape_at_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False, server_default=_NOW)
    created_at_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False, server_default=_NOW)

    __table_args__ = (Index("idx_routes_queue_due", "next_scrape_at_utc"),)


class Flight(Base):
    __tablename__ = "flights"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=False), primary_key=True)
    origin: Mapped[str] = mapped_column(String(3), nullable=False)
    destination: Mapped[str] = mapped_column(String(3), nullable=False)
    date: Mapped[date] = mapped_column(Date, nullable=False)
    airline: Mapped[str] = mapped_column(String(10), nullable=False)
    program: Mapped[str] = mapped_column(String(50), nullable=False)
    source: Mapped[str | None] = mapped_column(String(20))
    points_cost: Mapped[int] = mapped_column(Integer, nullable=False)
    cash_cost: Mapped[Decimal] = mapped_column(Numeric(8, 2), nullable=False, server_default=text("0.0"))
    stops: Mapped[int] = mapped_column(SmallInteger, nullable=False, server_default=text("0"))
    cabin_class: Mapped[str] = mapped_column(String(20), nullable=False)
    available_seats: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("-1"))
    # TEXT + NOT NULL DEFAULT 'UNKNOWN' (widened from VARCHAR(20); closes the NULLS-DISTINCT bypass)
    raw_flight_number: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'UNKNOWN'"))
    partner_airline: Mapped[str | None] = mapped_column(String(10))
    scraped_at_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    expires_at_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    departure_time_local: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    arrival_time_local: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    duration_minutes: Mapped[int | None] = mapped_column(Integer)
    aircraft_type: Mapped[str | None] = mapped_column(String(10))
    is_saver: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=_FALSE)
    fare_class: Mapped[str | None] = mapped_column(String(10))
    layover_airports: Mapped[str | None] = mapped_column(String)
    layover_duration_minutes: Mapped[int | None] = mapped_column(Integer)
    next_day_arrival: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=_FALSE)
    mixed_cabin: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=_FALSE)

    __table_args__ = (
        # Unnamed (as created inline in the applied DDL) — Postgres auto-names + 63-char-truncates.
        CheckConstraint("points_cost > 0"),
        CheckConstraint("cabin_class IN ('economy', 'premium_economy', 'business', 'first')"),
        UniqueConstraint(
            "origin", "destination", "date", "airline", "cabin_class", "raw_flight_number"
        ),
        Index("idx_flights_route_date", "origin", "destination", "date"),
        Index("idx_flights_program", "program", "cabin_class"),
        Index("idx_flights_route_date_cabin", "origin", "destination", "date", "cabin_class"),
        Index("idx_flights_route_airline", "origin", "destination", "airline"),
        Index("idx_flights_date", "date"),
        Index("idx_flights_expires", "expires_at_utc"),
    )


class CashFare(Base):
    __tablename__ = "cash_fares"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=False), primary_key=True)
    origin: Mapped[str] = mapped_column(String(3), nullable=False)
    destination: Mapped[str] = mapped_column(String(3), nullable=False)
    date: Mapped[date] = mapped_column(Date, nullable=False)
    airline: Mapped[str] = mapped_column(String(10), nullable=False)
    cabin_class: Mapped[str] = mapped_column(String(20), nullable=False)
    flight_number: Mapped[str] = mapped_column(String(20), nullable=False)
    cash_price: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, server_default=text("'USD'"))
    source: Mapped[str] = mapped_column(String(20), nullable=False, server_default=text("'google_flights'"))
    scraped_at_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    expires_at_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    __table_args__ = (
        CheckConstraint("cash_price > 0"),
        CheckConstraint("cabin_class IN ('economy', 'premium_economy', 'business', 'first')"),
        UniqueConstraint(
            "origin", "destination", "date", "airline", "cabin_class", "flight_number"
        ),
        Index("idx_cash_fares_route_date", "origin", "destination", "date"),
        Index("idx_cash_fares_route_date_cabin", "origin", "destination", "date", "cabin_class"),
        Index("idx_cash_fares_expires", "expires_at_utc"),
    )


class BankProgram(Base):
    __tablename__ = "bank_programs"

    id: Mapped[int] = mapped_column(SmallInteger, primary_key=True, autoincrement=False)
    name: Mapped[str] = mapped_column(String, nullable=False, unique=True)
    short_code: Mapped[str] = mapped_column(String(10), nullable=False, unique=True)
    created_at_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False, server_default=_NOW)


class TransferPartner(Base):
    __tablename__ = "transfer_partners"

    bank_program_id: Mapped[int] = mapped_column(SmallInteger, primary_key=True)
    airline_code: Mapped[str] = mapped_column(String(10), primary_key=True)
    program_name: Mapped[str] = mapped_column(String, nullable=False)
    transfer_ratio: Mapped[Decimal] = mapped_column(Numeric(5, 2), nullable=False, server_default=text("1.00"))
    min_transfer: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1000"))
    transfer_increment: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1000"))


class TransferBonus(Base):
    __tablename__ = "transfer_bonuses"

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=False), primary_key=True)
    bank_program_id: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    airline_code: Mapped[str] = mapped_column(String(10), nullable=False)
    bonus_pct: Mapped[int] = mapped_column(Integer, nullable=False)
    starts_at: Mapped[date] = mapped_column(Date, nullable=False)
    ends_at: Mapped[date] = mapped_column(Date, nullable=False)
    notes: Mapped[str | None] = mapped_column(String)
    created_at_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False, server_default=_NOW)
    updated_at_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False, server_default=_NOW)

    __table_args__ = (
        CheckConstraint("bonus_pct > 0"),
        CheckConstraint("ends_at >= starts_at"),
        UniqueConstraint("bank_program_id", "airline_code", "starts_at"),
        Index("idx_transfer_bonuses_active", "airline_code", "starts_at", "ends_at"),
    )


class OndemandCoverage(Base):
    __tablename__ = "ondemand_coverage"

    origin: Mapped[str] = mapped_column(String(3), primary_key=True)
    destination: Mapped[str] = mapped_column(String(3), primary_key=True)
    airline: Mapped[str] = mapped_column(String(10), primary_key=True)
    last_attempt_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    result_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    next_probe_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class CashCoverage(Base):
    __tablename__ = "cash_coverage"

    origin: Mapped[str] = mapped_column(String(3), primary_key=True)
    destination: Mapped[str] = mapped_column(String(3), primary_key=True)
    date: Mapped[date] = mapped_column(Date, primary_key=True)
    cabin: Mapped[str] = mapped_column(String(16), primary_key=True, server_default=text("'economy'"))
    last_attempt_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    fare_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    next_probe_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class AirlineBudget(Base):
    __tablename__ = "airline_budget"

    airline: Mapped[str] = mapped_column(String(10), primary_key=True)
    tokens: Mapped[float] = mapped_column(Double, nullable=False, server_default=text("0"))
    capacity: Mapped[float] = mapped_column(Double, nullable=False, server_default=text("0"))
    refill_per_hour: Mapped[float] = mapped_column(Double, nullable=False, server_default=text("0"))
    last_refill_utc: Mapped[datetime] = mapped_column(DateTime, nullable=False, server_default=_NOW)
